export type LanguageConfig = {
  code: string;
  name: string;
  nativeName: string;
  placeholder: string;
  ttsCode: string;
  ttsRate: number;
  script: 'latin' | 'hanzi' | 'kana' | 'hangul' | 'cyrillic' | 'arabic' | 'devanagari' | 'thai';
  hasPronunciationGuide: boolean;
  pronunciationLabel: string;
  flag: string;
};

export const LANGUAGES: LanguageConfig[] = [
  {
    code: 'zh-CN',
    name: 'Chinese (Mandarin)',
    nativeName: '中文',
    placeholder: '输入中文...',
    ttsCode: 'zh-CN',
    ttsRate: 0.85,
    script: 'hanzi',
    hasPronunciationGuide: true,
    pronunciationLabel: 'Pinyin',
    flag: '🇨🇳',
  },
  {
    code: 'ja',
    name: 'Japanese',
    nativeName: '日本語',
    placeholder: '日本語を入力...',
    ttsCode: 'ja-JP',
    ttsRate: 0.9,
    script: 'kana',
    hasPronunciationGuide: true,
    pronunciationLabel: 'Romaji',
    flag: '🇯🇵',
  },
  {
    code: 'ko',
    name: 'Korean',
    nativeName: '한국어',
    placeholder: '한국어를 입력하세요...',
    ttsCode: 'ko-KR',
    ttsRate: 0.95,
    script: 'hangul',
    hasPronunciationGuide: true,
    pronunciationLabel: 'Romanization',
    flag: '🇰🇷',
  },
  {
    code: 'es',
    name: 'Spanish',
    nativeName: 'Español',
    placeholder: 'Escribe en español...',
    ttsCode: 'es-ES',
    ttsRate: 1.0,
    script: 'latin',
    hasPronunciationGuide: false,
    pronunciationLabel: '',
    flag: '🇪🇸',
  },
  {
    code: 'fr',
    name: 'French',
    nativeName: 'Français',
    placeholder: 'Écrivez en français...',
    ttsCode: 'fr-FR',
    ttsRate: 1.0,
    script: 'latin',
    hasPronunciationGuide: false,
    pronunciationLabel: '',
    flag: '🇫🇷',
  },
  {
    code: 'de',
    name: 'German',
    nativeName: 'Deutsch',
    placeholder: 'Auf Deutsch schreiben...',
    ttsCode: 'de-DE',
    ttsRate: 1.0,
    script: 'latin',
    hasPronunciationGuide: false,
    pronunciationLabel: '',
    flag: '🇩🇪',
  },
  {
    code: 'it',
    name: 'Italian',
    nativeName: 'Italiano',
    placeholder: 'Scrivi in italiano...',
    ttsCode: 'it-IT',
    ttsRate: 1.0,
    script: 'latin',
    hasPronunciationGuide: false,
    pronunciationLabel: '',
    flag: '🇮🇹',
  },
  {
    code: 'pt-BR',
    name: 'Portuguese (Brazil)',
    nativeName: 'Português',
    placeholder: 'Escreva em português...',
    ttsCode: 'pt-BR',
    ttsRate: 1.0,
    script: 'latin',
    hasPronunciationGuide: false,
    pronunciationLabel: '',
    flag: '🇧🇷',
  },
  {
    code: 'ru',
    name: 'Russian',
    nativeName: 'Русский',
    placeholder: 'Напишите по-русски...',
    ttsCode: 'ru-RU',
    ttsRate: 0.95,
    script: 'cyrillic',
    hasPronunciationGuide: true,
    pronunciationLabel: 'Transliteration',
    flag: '🇷🇺',
  },
  {
    code: 'ar',
    name: 'Arabic',
    nativeName: 'العربية',
    placeholder: '...اكتب بالعربية',
    ttsCode: 'ar-SA',
    ttsRate: 0.95,
    script: 'arabic',
    hasPronunciationGuide: true,
    pronunciationLabel: 'Transliteration',
    flag: '🇸🇦',
  },
  {
    code: 'hi',
    name: 'Hindi',
    nativeName: 'हिन्दी',
    placeholder: 'हिन्दी में लिखें...',
    ttsCode: 'hi-IN',
    ttsRate: 0.95,
    script: 'devanagari',
    hasPronunciationGuide: true,
    pronunciationLabel: 'Transliteration',
    flag: '🇮🇳',
  },
  {
    code: 'th',
    name: 'Thai',
    nativeName: 'ไทย',
    placeholder: 'เขียนภาษาไทย...',
    ttsCode: 'th-TH',
    ttsRate: 0.9,
    script: 'thai',
    hasPronunciationGuide: true,
    pronunciationLabel: 'Transliteration',
    flag: '🇹🇭',
  },
  {
    code: 'vi',
    name: 'Vietnamese',
    nativeName: 'Tiếng Việt',
    placeholder: 'Viết tiếng Việt...',
    ttsCode: 'vi-VN',
    ttsRate: 0.95,
    script: 'latin',
    hasPronunciationGuide: false,
    pronunciationLabel: '',
    flag: '🇻🇳',
  },
  {
    code: 'tr',
    name: 'Turkish',
    nativeName: 'Türkçe',
    placeholder: 'Türkçe yazın...',
    ttsCode: 'tr-TR',
    ttsRate: 1.0,
    script: 'latin',
    hasPronunciationGuide: false,
    pronunciationLabel: '',
    flag: '🇹🇷',
  },
  {
    code: 'id',
    name: 'Indonesian',
    nativeName: 'Bahasa Indonesia',
    placeholder: 'Tulis dalam bahasa Indonesia...',
    ttsCode: 'id-ID',
    ttsRate: 1.0,
    script: 'latin',
    hasPronunciationGuide: false,
    pronunciationLabel: '',
    flag: '🇮🇩',
  },
  {
    code: 'en',
    name: 'English',
    nativeName: 'English',
    placeholder: 'Enter word or phrase...',
    ttsCode: 'en-US',
    ttsRate: 1.0,
    script: 'latin',
    hasPronunciationGuide: false,
    pronunciationLabel: '',
    flag: '🇺🇸',
  },
];

export const DEFAULT_LANGUAGE_CODE = 'zh-CN';

export function getLanguageByCode(code: string): LanguageConfig {
  return LANGUAGES.find((l) => l.code === code) ?? LANGUAGES[0];
}
